src/main/java/main/Model.java

I have added the model to be used in the board game.

Added model

---

src/main/java/main/BeadIcon.java

Made radius a bit smaller, drew black outline, need approval.

BeadIcon Updates

---

src/main/java/main/Model.java

Added version number in Model.java.

Verison Number

---

src/main/java/main/BeadIcon.java

Fixing verison number on BeadIcon.java

Verison Fix BeadIcon.java

---

src/main/java/main/PitsPanel.java

Displays and stores the 12 pits for the Mancala Board game

Added Pits Panel 

---

src/main/java/main/BeadPainter.java
src/main/java/main/Pit.java
src/test/java/PitTest.java

Fixed the bug "Pit doesn't have a preferred size"
added setPreferredSize method to the constructor.
Created PitTest which tests the Pit class
Pit now stores beads in an ArrayList instead of creating them in PaintComponent.
Beads get painted by BeadPainter
Added a mouse adapter to be used later

Fixed bug "Pit doesn't have a preferred size"

---

src/main/java/main/BeadIcon.java

Hey team,
The beadicons were recoloring themselves when staying in the same pit if the frame was adjusted and it was unnecessarily repainting itself, thereby requiring a fix. It should work, let me know if there are any issues.

BeadIcon recoloring fix

---

src/main/java/main/PitsPanel.java

Changed the GridLayout to contain parameters for the gaps between each of the pits.

Adding gaps to Pits Panel 

---

src/main/java/main/MancalaBoard.java
src/main/java/main/PitsPanel.java

Edited the PitsPanel class to add labels to the pits, and changed made sure fontColor of the labels can be changed

Adding labels

---

src/main/java/Styles/BoardStyle.java
src/main/java/Styles/BoardStylePicker.java
src/main/java/Styles/DarkModeStyle.java
src/main/java/Styles/DefaultBoardStyle.java
src/main/java/Styles/KimStyle.java
src/main/java/main/GameStatus.java
src/main/java/main/MancalaBoard.java

Added a new style which matches the colors on Kim's website. 
I also moved all the styles into a new package to be more organized.

Added Kim Style

---

.idea/gradle.xml
.idea/misc.xml
src/main/java/main/GameStatus.java
src/main/java/main/MancalaBoard.java
src/main/java/styles/BoardStyle.java
src/main/java/styles/BoardStylePicker.java
src/main/java/styles/DarkModeStyle.java
src/main/java/styles/DefaultBoardStyle.java
src/main/java/styles/KimStyle.java

Fixed capatalization of styles

---

src/main/java/main/Mancala.java
src/main/java/main/MancalaBoard.java
src/main/java/main/Pit.java
src/main/java/main/PitsPanel.java

added class to manage the game logic in mancala game

mancala class backend 

---

src/main/java/main/GameStatus.java
src/main/java/main/styles/ClownStyle.java

set board to red and yellow for clown style

added clown  style

---

src/main/java/main/Pit.java

Added getOppositePitOf(int pitNumber) method which returns an integer for the opposite pit.

Added method to Pit which gets the opposite pit

---

src/main/java/main/Undo.java

undo counter

---

src/main/java/main/GameStatus.java
src/main/java/main/Pit.java
src/main/java/main/Undo.java

Added the player turn system functionality. It is initialized so far so that player B aalways goes first. This will get updated later.

Added the player turn system

---

src/main/java/main/GameStatus.java

Adjusted the default game start to allow the players to determine who goes first.

Player Turn Game Start settings

---

src/main/java/main/Pit.java

Fixed the index out of bounds bug that could happen

Fixed, yet another bug

---

src/main/java/main/GameStatus.java
src/main/java/main/Victory.java

Victory class and small edits for us to be able to determine winner of game.

VICTORY CLASS

---

src/main/java/main/Pit.java

Added the victory check condition.

Added victory check condition

---

src/main/java/main/Pit.java

Added the final game rule which allows a player to go again if the last bead they placed is in their Mancala.

Added the final game rule

---

src/main/java/main/Pit.java

Small condition check to see whether the pit is empty. If it is empty the player cannot click on it and use a turn.

Added small condition

---

src/main/java/main/Pit.java

fixed the bug where the player can only steal beads if the last bead is in their own pit

stealing beads bug

---

src/main/java/main/MancalaPit.java

MancalaPit name owner labels
